---
- name: install required Packages
  yum:
    name: "{{ items }}"
    with_items:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    state: present

- name: Add docker CE repository
  yum_repository:
    name: docker-ce
    description: Docker CE YUM repo
    baseurl: https://download.docker.com/linux/centos/docker-ce.repo

- name: download Docker CE v1.12
  get_url:
    url: https://releases.rancher.com/install-docker/1.12.sh
    dest: /tmp/docker/1.12.sh
    mode: 0700

- name: install Docker CE v1.12
  script: /tmp/docker/1.12.sh
